# Generated by Django 5.1.6 on 2025-09-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delais', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delai',
            options={'ordering': ['-date_debut']},
        ),
        migrations.AlterField(
            model_name='delai',
            name='actif',
            field=models.BooleanField(default=True, help_text='Décochez pour désactiver manuellement ce délai'),
        ),
    ]
