# Generated by Django 5.1.6 on 2025-08-26 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiants', '0001_initial'),
        ('jury', '0001_initial'),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('fichier_joint', models.FileField(blank=True, null=True, upload_to='recours_fichiers/')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('ENVOYE', 'Envoyé'), ('EN_COURS', 'En cours de traitement'), ('ACCEPTE', 'Accepté'), ('REJETE', 'Rejeté')], default='ENVOYE', max_length=20)),
                ('decision', models.TextField(blank=True, null=True)),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recours', to='structure.domaine')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recours', to='etudiants.etudiantprofile')),
                ('jury_assigne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recours_assignes', to='jury.juryprofile')),
            ],
        ),
    ]
