# Generated by Django 5.1.6 on 2025-08-26 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JuryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonction', models.CharField(help_text='Ex: Président, Membre, Rapporteur', max_length=150)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jurys', to='structure.domaine')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jury_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
