# Generated by Django 5.1.6 on 2025-09-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juryprofile',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='photos_jury/'),
        ),
    ]
