# Generated by Django 5.1.6 on 2025-09-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0002_juryprofile_photo_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juryprofile',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='photos_jurys/'),
        ),
    ]
