# Generated by Django 5.1.6 on 2025-09-21 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0003_alter_juryprofile_photo_profil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juryprofile',
            name='telephone',
        ),
    ]
