# Generated by Django 5.1.6 on 2025-09-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ETU', 'Étudiant'), ('JUR', 'Jury'), ('STA', 'Staff/Administration')], default='ETU', help_text="Rôle fonctionnel de l'utilisateur", max_length=3),
        ),
    ]
